services:
  postgres_dev:
    image: postgres:16
    container_name: bloom_postgres_dev
    environment:
      POSTGRES_USER: ${user}           # Переменная из .env
      POSTGRES_PASSWORD: ${password}   # Переменная из .env
      POSTGRES_DB: ${db_name}          # Переменная из .env
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${user} -d ${db_name}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis_dev:
    image: redis:7.4-alpine  # легковесный образ
    container_name: bloom_redis_dev
    ports:
      - "6379:6379"  # стандартный порт Redis
    volumes:
      - redis_data_dev:/data  # монтируем объём для данных
    command: redis-server --appendonly yes  # включаем сохранение на диск
    restart: unless-stopped
    networks:
      - pricely_network

  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: bloom_redis_commander
    environment:
      - REDIS_HOSTS=local:redis_dev:6379
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - pricely_network

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  pricely_network:
    driver: bridge