services:
  postgres_dev:
    image: postgres:16
    container_name: bloom_postgres_dev
    environment:
      POSTGRES_USER: ${user}           # Переменная из .env
      POSTGRES_PASSWORD: ${password}   # Переменная из .env
      POSTGRES_DB: ${db_name}          # Переменная из .env
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${pg_user} -d ${pg_db_name}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data_dev:
    driver: local

networks:
  pricely_network:
    driver: bridge
